//
// Created by AmirHosein on 1/27/2018 AD.
//

#ifndef MUSIC_SIMILARITIES_CACHE_RECOMMENDER_HPP
#define MUSIC_SIMILARITIES_CACHE_RECOMMENDER_HPP

void run_recommender();

#endif //MUSIC_SIMILARITIES_CACHE_RECOMMENDER_HPP
